// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx9nBYKm4txvIss_WskraBcvsHQ8eexac',
    appId: '1:1064906268705:web:c150201340c984fd2c4360',
    messagingSenderId: '1064906268705',
    projectId: 'app-learning-vietnamese',
    authDomain: 'app-learning-vietnamese.firebaseapp.com',
    storageBucket: 'app-learning-vietnamese.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzwnf68m14NRi0Z5VDK0iNAzWuLqlnLSA',
    appId: '1:1064906268705:android:cccac159c79f57d02c4360',
    messagingSenderId: '1064906268705',
    projectId: 'app-learning-vietnamese',
    storageBucket: 'app-learning-vietnamese.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKZXdDa9lAUwnK5HylF8mLYlNPwH3k0I0',
    appId: '1:1064906268705:ios:fd393b5499b7bda62c4360',
    messagingSenderId: '1064906268705',
    projectId: 'app-learning-vietnamese',
    storageBucket: 'app-learning-vietnamese.firebasestorage.app',
    iosBundleId: 'com.example.appHocTiengViet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKZXdDa9lAUwnK5HylF8mLYlNPwH3k0I0',
    appId: '1:1064906268705:ios:fd393b5499b7bda62c4360',
    messagingSenderId: '1064906268705',
    projectId: 'app-learning-vietnamese',
    storageBucket: 'app-learning-vietnamese.firebasestorage.app',
    iosBundleId: 'com.example.appHocTiengViet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx9nBYKm4txvIss_WskraBcvsHQ8eexac',
    appId: '1:1064906268705:web:60d66315cacaf12d2c4360',
    messagingSenderId: '1064906268705',
    projectId: 'app-learning-vietnamese',
    authDomain: 'app-learning-vietnamese.firebaseapp.com',
    storageBucket: 'app-learning-vietnamese.firebasestorage.app',
  );
}
